// <auto-generated />
using System;
using DotnetCore21.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DotnetCore21.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20180701051141_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DotnetCore21.Models.Character.A_Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Act")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<int>("Agility");

                    b.Property<string>("Description");

                    b.Property<int>("Fatness");

                    b.Property<int>("Femininity");

                    b.Property<int>("Fitness");

                    b.Property<int>("Intelligence");

                    b.Property<int>("Luck");

                    b.Property<int>("Masculinity");

                    b.Property<int>("Race");

                    b.Property<int>("Strength");

                    b.Property<DateTime>("TS");

                    b.Property<string>("Title");

                    b.Property<int>("Vitality");

                    b.Property<int>("Willpower");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("DotnetCore21.Models.Character.Arm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("A_CharacterId");

                    b.Property<string>("Act")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<string>("Description");

                    b.Property<int>("Skin");

                    b.Property<DateTime>("TS");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("A_CharacterId");

                    b.ToTable("Arm");
                });

            modelBuilder.Entity("DotnetCore21.Models.Character.Core", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("A_CharacterId");

                    b.Property<string>("Act")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<string>("Description");

                    b.Property<int>("Skin");

                    b.Property<DateTime>("TS");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("A_CharacterId");

                    b.ToTable("Core");
                });

            modelBuilder.Entity("DotnetCore21.Models.Character.Foot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("A_CharacterId");

                    b.Property<string>("Act")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<string>("Description");

                    b.Property<int>("Skin");

                    b.Property<DateTime>("TS");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("A_CharacterId");

                    b.ToTable("Foot");
                });

            modelBuilder.Entity("DotnetCore21.Models.Character.Hand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("A_CharacterId");

                    b.Property<string>("Act")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<string>("Description");

                    b.Property<int>("Skin");

                    b.Property<DateTime>("TS");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("A_CharacterId");

                    b.ToTable("Hand");
                });

            modelBuilder.Entity("DotnetCore21.Models.Character.Head", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("A_CharacterId");

                    b.Property<string>("Act")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<string>("Description");

                    b.Property<int>("Skin");

                    b.Property<DateTime>("TS");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("A_CharacterId");

                    b.ToTable("Head");
                });

            modelBuilder.Entity("DotnetCore21.Models.Character.Leg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("A_CharacterId");

                    b.Property<string>("Act")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<string>("Description");

                    b.Property<int>("Skin");

                    b.Property<DateTime>("TS");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("A_CharacterId");

                    b.ToTable("Leg");
                });

            modelBuilder.Entity("DotnetCore21.Models.Character.Shoulder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("A_CharacterId");

                    b.Property<string>("Act")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<string>("Description");

                    b.Property<int>("Skin");

                    b.Property<DateTime>("TS");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("A_CharacterId");

                    b.ToTable("Shoulder");
                });

            modelBuilder.Entity("DotnetCore21.Models.Character.Waist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("A_CharacterId");

                    b.Property<string>("Act")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<string>("Description");

                    b.Property<int>("Skin");

                    b.Property<DateTime>("TS");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("A_CharacterId");

                    b.ToTable("Waist");
                });

            modelBuilder.Entity("DotnetCore21.Models.Item.A_Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("A_CharacterId");

                    b.Property<int?>("A_CharacterId1");

                    b.Property<string>("Act")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<string>("Description");

                    b.Property<DateTime>("TS");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("A_CharacterId");

                    b.HasIndex("A_CharacterId1");

                    b.ToTable("A_Item");
                });

            modelBuilder.Entity("DotnetCore21.Models.Movie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Genre");

                    b.Property<decimal>("Price");

                    b.Property<DateTime>("ReleaseDate");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Movie");
                });

            modelBuilder.Entity("DotnetCore21.Models.Character.Arm", b =>
                {
                    b.HasOne("DotnetCore21.Models.Character.A_Character")
                        .WithMany("Arms")
                        .HasForeignKey("A_CharacterId");
                });

            modelBuilder.Entity("DotnetCore21.Models.Character.Core", b =>
                {
                    b.HasOne("DotnetCore21.Models.Character.A_Character")
                        .WithMany("Core")
                        .HasForeignKey("A_CharacterId");
                });

            modelBuilder.Entity("DotnetCore21.Models.Character.Foot", b =>
                {
                    b.HasOne("DotnetCore21.Models.Character.A_Character")
                        .WithMany("Feet")
                        .HasForeignKey("A_CharacterId");
                });

            modelBuilder.Entity("DotnetCore21.Models.Character.Hand", b =>
                {
                    b.HasOne("DotnetCore21.Models.Character.A_Character")
                        .WithMany("Hands")
                        .HasForeignKey("A_CharacterId");
                });

            modelBuilder.Entity("DotnetCore21.Models.Character.Head", b =>
                {
                    b.HasOne("DotnetCore21.Models.Character.A_Character")
                        .WithMany("Heads")
                        .HasForeignKey("A_CharacterId");
                });

            modelBuilder.Entity("DotnetCore21.Models.Character.Leg", b =>
                {
                    b.HasOne("DotnetCore21.Models.Character.A_Character")
                        .WithMany("Legs")
                        .HasForeignKey("A_CharacterId");
                });

            modelBuilder.Entity("DotnetCore21.Models.Character.Shoulder", b =>
                {
                    b.HasOne("DotnetCore21.Models.Character.A_Character")
                        .WithMany("Shoulders")
                        .HasForeignKey("A_CharacterId");
                });

            modelBuilder.Entity("DotnetCore21.Models.Character.Waist", b =>
                {
                    b.HasOne("DotnetCore21.Models.Character.A_Character")
                        .WithMany("Waist")
                        .HasForeignKey("A_CharacterId");
                });

            modelBuilder.Entity("DotnetCore21.Models.Item.A_Item", b =>
                {
                    b.HasOne("DotnetCore21.Models.Character.A_Character")
                        .WithMany("Equipment")
                        .HasForeignKey("A_CharacterId");

                    b.HasOne("DotnetCore21.Models.Character.A_Character")
                        .WithMany("Inventory")
                        .HasForeignKey("A_CharacterId1");
                });
#pragma warning restore 612, 618
        }
    }
}
